/**
 * Русские имена меток AniList.
 *
 * Зачем: вектор тона состоит из одних только меток, и язык в нём решает.
 * Замер на «Лагере на свежем воздухе» — тот же набор меток по-английски и
 * по-русски против запроса «что-нибудь тихое и уютное, чтобы отдохнуть»:
 * 0.320 против 0.466. Это больше, чем дала любая правка состава за все дни.
 *
 * Раньше перевод меток не давал ничего (состав v3, сменился один тайтл из
 * пяти), но там десяток слов тонул в пятистах символах русского синопсиса
 * рядом. В отдельном векторе тона рядом с ними нет ничего.
 *
 * Переведены 250 меток из 401 — они покрывают 97.5% всех связей. Остальные
 * это редкая экзотика и откровенная порнография; они остаются английскими,
 * см. запасной вариант в aniWords.
 */
export const ANITAG_RU: Record<string, string> = {
  // Кто в кадре
  "Male Protagonist": "Главный герой — мужчина",
  "Female Protagonist": "Главная героиня — женщина",
  "Primarily Female Cast": "Преимущественно женский состав",
  "Primarily Male Cast": "Преимущественно мужской состав",
  "Primarily Adult Cast": "Взрослые персонажи",
  "Primarily Teen Cast": "Подростки",
  "Primarily Child Cast": "Дети",
  "Primarily Animal Cast": "Животные вместо людей",
  "Ensemble Cast": "Много главных героев",
  "Anti-Hero": "Антигерой",
  Villainess: "Злодейка",
  Superhero: "Супергерой",
  "Elderly Protagonist": "Пожилой главный герой",

  // Характеры и типажи
  Kuudere: "Холодная и сдержанная героиня",
  Tsundere: "Цундэрэ, колючая снаружи и мягкая внутри",
  Yandere: "Яндэрэ, одержимая любовью до безумия",
  "Ojou-sama": "Барышня из богатой семьи",
  Tomboy: "Пацанка",
  Gyaru: "Гяру",
  Chuunibyou: "Подросток, вообразивший себя избранным",
  Hikikomori: "Затворник, не выходящий из дома",
  Delinquents: "Хулиганы и школьная шпана",
  Maids: "Горничные",
  Butler: "Дворецкий",
  "Office Lady": "Офисная сотрудница",
  Teacher: "Учитель",
  Nun: "Монахиня",
  "Shrine Maiden": "Жрица синтоистского храма",
  Twins: "Близнецы",
  Orphan: "Сирота",
  Femboy: "Женственный юноша",

  // Настроение и подача
  Iyashikei: "Исцеляющее и умиротворяющее",
  "Cute Girls Doing Cute Things": "Милые девочки занимаются милыми делами",
  "Cute Boys Doing Cute Things": "Милые юноши занимаются милыми делами",
  "Coming of Age": "Взросление",
  "Family Life": "Семейная жизнь",
  "Found Family": "Обретённая семья",
  Parenthood: "Родительство",
  Slapstick: "Балаганная комедия",
  "Surreal Comedy": "Сюрреалистичная комедия",
  Satire: "Сатира",
  Parody: "Пародия",
  Meta: "Ирония над самим жанром",
  Philosophy: "Философское",
  Educational: "Познавательное",
  Denpa: "Тревожное и болезненное",
  "Body Horror": "Телесный ужас",
  "Cosmic Horror": "Космический ужас",
  Gore: "Жестокость и кровь",
  Psychosexual: "Психосексуальное",
  Noir: "Нуар",
  Dystopian: "Антиутопия",
  Achromatic: "Чёрно-белое",
  "No Dialogue": "Без слов",
  Episodic: "Отдельные истории в каждой серии",
  "Achronological Order": "События не по порядку",
  Anthology: "Сборник историй",
  Crossover: "Пересечение разных вселенных",
  Anachronism: "Смешение эпох",
  "Mixed Media": "Смешение техник",
  POV: "Взгляд от первого лица",

  // Жанровые опоры
  Magic: "Магия",
  "Urban Fantasy": "Городское фэнтези",
  Isekai: "Попадание в другой мир",
  "Reverse Isekai": "Гость из другого мира у нас",
  "Super Power": "Сверхспособности",
  Henshin: "Превращение в героя",
  Mythology: "Мифология",
  Gods: "Боги",
  Angels: "Ангелы",
  Demons: "Демоны",
  Youkai: "Ёкаи, японская нечисть",
  Ghost: "Призраки",
  Vampire: "Вампиры",
  Werewolf: "Оборотни",
  Zombie: "Зомби",
  Skeleton: "Скелеты и нежить",
  Mermaid: "Русалки",
  Dragons: "Драконы",
  Elf: "Эльфы",
  Fairy: "Феи",
  Witch: "Ведьмы",
  Kemonomimi: "Персонажи со звериными ушами",
  Nekomimi: "Кошачьи ушки",
  "Monster Girl": "Девушка-монстр",
  "Monster Boy": "Юноша-монстр",
  Kaiju: "Гигантские чудовища",
  Dinosaurs: "Динозавры",
  Shapeshifting: "Оборотничество и смена облика",
  Curses: "Проклятия",
  Exorcism: "Изгнание духов",
  Necromancy: "Некромантия",
  Alchemy: "Алхимия",
  Cultivation: "Совершенствование по восточным канонам",
  Prophecy: "Пророчество",

  // Фантастика и техника
  Robots: "Роботы",
  "Real Robot": "Реалистичные боевые роботы",
  "Super Robot": "Супер-роботы",
  Cyborg: "Киборги",
  Aliens: "Инопланетяне",
  Space: "Космос",
  "Space Opera": "Космическая опера",
  Cyberpunk: "Киберпанк",
  Steampunk: "Стимпанк",
  "Artificial Intelligence": "Искусственный интеллект",
  "Virtual World": "Виртуальный мир",
  "Augmented Reality": "Дополненная реальность",
  "Video Games": "Видеоигры",
  "Card Battle": "Карточные сражения",
  "Proxy Battle": "Бои через посредников",
  "Post-Apocalyptic": "После конца света",
  "Lost Civilization": "Погибшая цивилизация",
  Clone: "Клоны",
  "Software Development": "Программирование",
  Ships: "Корабли",
  Aviation: "Авиация",
  Trains: "Поезда",
  Cars: "Автомобили",
  Motorcycles: "Мотоциклы",
  Tanks: "Танки",
  Mopeds: "Мопеды",

  // Место и время
  School: "Школа",
  "School Club": "Школьный клуб",
  College: "Университет",
  "Boarding School": "Школа-интернат",
  Urban: "Город",
  Rural: "Сельская местность",
  Coastal: "Побережье",
  Desert: "Пустыня",
  Snowscape: "Снежные пейзажи",
  Wilderness: "Дикая природа",
  Historical: "Историческое",
  Medieval: "Средневековье",
  "Ancient China": "Древний Китай",
  Foreign: "Действие за пределами Японии",
  Dungeon: "Подземелья",
  Environmental: "Про природу и экологию",
  Office: "Офис",
  Restaurant: "Ресторан",
  Bar: "Бар",
  Inn: "Постоялый двор",
  Konbini: "Круглосуточный магазинчик",
  Prison: "Тюрьма",

  // Действие
  War: "Война",
  Military: "Военное",
  Swordplay: "Бой на мечах",
  Spearplay: "Бой на копьях",
  Archery: "Стрельба из лука",
  Guns: "Огнестрельное оружие",
  "Martial Arts": "Боевые искусства",
  Samurai: "Самураи",
  Ninja: "Ниндзя",
  Assassins: "Наёмные убийцы",
  Wuxia: "Уся, странствующие бойцы",
  "Battle Royale": "Бой на выживание всех против всех",
  "Death Game": "Смертельная игра",
  Survival: "Выживание",
  Revenge: "Месть",
  Fugitive: "Беглец",
  Espionage: "Шпионаж",
  Terrorism: "Терроризм",
  Crime: "Преступность",
  Police: "Полиция",
  Detective: "Детектив",
  Mafia: "Мафия",
  Yakuza: "Якудза",
  Gangs: "Банды",
  "Criminal Organization": "Преступная организация",
  Triads: "Триады",
  Conspiracy: "Заговор",
  Politics: "Политика",
  "Kingdom Management": "Управление королевством",
  "Royal Affairs": "Придворные интриги",
  "Class Struggle": "Классовая борьба",
  Economics: "Экономика",
  Religion: "Религия",
  Cult: "Секта",
  Slavery: "Рабство",
  Torture: "Пытки",
  Bullying: "Травля",
  Rehabilitation: "Возвращение к жизни",
  "Human Experimentation": "Опыты над людьми",
  "Memory Manipulation": "Стирание и подмена памяти",
  Amnesia: "Потеря памяти",
  "Dissociative Identities": "Расщепление личности",
  Brainwashing: "Промывание мозгов",
  Drugs: "Наркотики",
  Pandemic: "Эпидемия",
  Medicine: "Медицина",
  Disability: "Инвалидность",
  Suicide: "Самоубийство",
  "Natural Disaster": "Стихийное бедствие",

  // Отношения
  Heterosexual: "Отношения мужчины и женщины",
  Yuri: "Отношения между девушками",
  "Boys' Love": "Отношения между юношами",
  "Teens' Love": "Подростковая любовь",
  "LGBTQ+ Themes": "ЛГБТ-темы",
  Bisexual: "Бисексуальность",
  Asexual: "Асексуальность",
  Aromantic: "Аромантичность",
  Transgender: "Трансгендерность",
  Agender: "Вне гендера",
  "Gender Bending": "Смена пола",
  Crossdressing: "Переодевание в другой пол",
  "Love Triangle": "Любовный треугольник",
  "Unrequited Love": "Безответная любовь",
  "Female Harem": "Гарем из девушек",
  "Male Harem": "Гарем из юношей",
  "Mixed Gender Harem": "Смешанный гарем",
  Marriage: "Брак",
  "Arranged Marriage": "Брак по договорённости",
  "Fake Relationship": "Отношения понарошку",
  Cohabitation: "Совместная жизнь под одной крышей",
  "Estranged Family": "Разлад в семье",
  Adoption: "Усыновление",
  Matchmaking: "Сватовство",
  Polyamorous: "Полиамория",
  Incest: "Инцест",
  Cheating: "Измена",
  Blackmail: "Шантаж",
  "Language Barrier": "Языковой барьер",
  Interspecies: "Отношения между разными видами",

  // Занятия и увлечения
  Food: "Еда и готовка",
  "Outdoor Activities": "Отдых на природе",
  Camping: "Кемпинг",
  Fishing: "Рыбалка",
  Travel: "Путешествия",
  Agriculture: "Сельское хозяйство",
  Horticulture: "Садоводство",
  Animals: "Животные",
  "Creature Taming": "Приручение существ",
  Idol: "Идолы и поп-сцена",
  Band: "Музыкальная группа",
  "Rock Music": "Рок",
  "Classical Music": "Классическая музыка",
  "Jazz Music": "Джаз",
  "Metal Music": "Метал",
  "Hip-hop Music": "Хип-хоп",
  "Vocal Synth": "Синтезированный вокал",
  Dancing: "Танцы",
  "Musical Theater": "Мюзикл",
  Acting: "Актёрство",
  Drawing: "Рисование",
  Writing: "Литературное творчество",
  Photography: "Фотография",
  Filmmaking: "Кино изнутри",
  Fashion: "Мода",
  Cosplay: "Косплей",
  "Otaku Culture": "Культура отаку",
  VTuber: "Виртуальные блогеры",
  Astronomy: "Астрономия",
  Gambling: "Азартные игры",
  "Board Game": "Настольные игры",
  Mahjong: "Маджонг",
  Shogi: "Сёги",
  Go: "Го",
  Karuta: "Карута",
  Rakugo: "Ракуго",
  Calligraphy: "Каллиграфия",
  Kabuki: "Кабуки",
  Circus: "Цирк",
  Puppetry: "Кукольный театр",
  Advertisement: "Реклама",
  Work: "Работа",

  // Спорт
  Athletics: "Лёгкая атлетика",
  Baseball: "Бейсбол",
  Basketball: "Баскетбол",
  Football: "Футбол",
  "American Football": "Американский футбол",
  Volleyball: "Волейбол",
  Tennis: "Теннис",
  "Table Tennis": "Настольный теннис",
  Badminton: "Бадминтон",
  Swimming: "Плавание",
  Boxing: "Бокс",
  Wrestling: "Борьба",
  Judo: "Дзюдо",
  Sumo: "Сумо",
  Fencing: "Фехтование",
  Cycling: "Велоспорт",
  "Ice Sports": "Ледовые виды спорта",
  Surfing: "Сёрфинг",
  Skateboarding: "Скейтбординг",
  Mountaineering: "Альпинизм",
  Golf: "Гольф",
  Rugby: "Регби",
  Handball: "Гандбол",
  Lacrosse: "Лакросс",
  Bowling: "Боулинг",
  Poker: "Покер",
  "E-Sports": "Киберспорт",
  Fitness: "Спортзал и тренировки",
  Acrobatics: "Акробатика",
  Parkour: "Паркур",
  Cheerleading: "Черлидинг",
  Ballet: "Балет",
  Airsoft: "Страйкбол",
  "Scuba Diving": "Дайвинг",
  Firefighters: "Пожарные",
  Veterinarian: "Ветеринар",

  // Демография и формат
  Shounen: "Для юношей",
  Shoujo: "Для девушек",
  Seinen: "Для взрослых мужчин",
  Josei: "Для взрослых женщин",
  Kids: "Детское",
  Chibi: "Укороченные пропорции персонажей",
  CGI: "Компьютерная графика",
  "Full CGI": "Полностью в компьютерной графике",
  "Stop Motion": "Покадровая анимация",
  Rotoscoping: "Ротоскопирование",
  Flash: "Анимация во Flash",
  Tokusatsu: "Токусацу",
  "Classic Literature": "По классической литературе",
  "Fairy Tale": "Сказка",
  Biographical: "Биографическое",
  Autobiographical: "Автобиографическое",
  "Non-fiction": "Документальное",
  Anthropomorphism: "Очеловеченные предметы и звери",
  "Age Regression": "Превращение во что-то младшее",
  "Time Loop": "Временная петля",
  Nudity: "Обнажённость",
  "Large Breasts": "Большая грудь",
  "Flat Chest": "Плоская грудь",
  "Tanned Skin": "Загорелая кожа",
  Makeup: "Макияж",
  "Body Image": "Отношение к своему телу",
  Pregnancy: "Беременность",
  Rape: "Изнасилование",
  Prostitution: "Проституция",
  Succubus: "Суккубы",
  Goblin: "Гоблины",
  Centaur: "Кентавры",
  Dullahan: "Дуллахан",
  Chimera: "Химеры",
  Matriarchy: "Матриархат",
  Homeless: "Бездомные",
  Exiled: "Изгнанник",
  Vikings: "Викинги",
  Pirates: "Пираты",
  Cowboys: "Ковбои",
  "Indigenous Cultures": "Коренные народы",
  "Middle east": "Ближний Восток",
  Oiran: "Ойран",
  Graduation: "Выпуск из школы",
  "Ero Guro": "Эро-гуро",
  "Eco-Horror": "Экологический ужас",
  Cannibalism: "Каннибализм",
  Amputation: "Ампутация",
};
